"""Reads the software bill of materials bundled at build time.

mountie/data/sbom.json is a static snapshot generated by
scripts/generate_sbom.py from the Flatpak manifest and pyproject.toml, not
something computed from the running process, so it describes the build
Mountie shipped in rather than whatever happens to be on this machine.
"""

import json
from importlib import resources


def load_sbom():
    """Return the parsed SBOM, or None if this build didn't bundle one."""
    try:
        text = resources.files("mountie").joinpath("data/sbom.json").read_text(
            encoding="utf-8"
        )
    except (FileNotFoundError, OSError):
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return None


def format_sbom(sbom):
    """Render a parsed SBOM as a short, human-readable component list."""
    app = sbom["metadata"]["component"]
    lines = [
        f"Mountie {app['version']}",
        f"Generated {sbom['metadata']['timestamp']}",
        "",
        "Components:",
    ]
    for component in sbom["components"]:
        lines.append(f"  {component['name']}  {component['version']}")
    return "\n".join(lines)
